"""Stable, path-safe errors for the media boundary."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Literal

MediaErrorCode = Literal[
    "MEDIA_TOOL_UNAVAILABLE",
    "MEDIA_TOOL_TIMEOUT",
    "MEDIA_PROBE_PARSE_ERROR",
    "MEDIA_NOT_MEDIA",
    "MEDIA_OUTPUT_INVALID",
    "MEDIA_CANCELLED",
    "TRANSCRIPTION_TOOL_UNAVAILABLE",
    "TRANSCRIPTION_MODEL_UNAVAILABLE",
    "TRANSCRIPTION_OUTPUT_INVALID",
    "TRANSCRIPTION_TIMEOUT",
    "TRANSCRIPTION_CANCELLED",
    "VAD_TOOL_UNAVAILABLE",
    "VAD_OUTPUT_INVALID",
    "VAD_TIMEOUT",
    "VAD_CANCELLED",
    "SENTENCE_PREREQUISITE_UNAVAILABLE",
    "SENTENCE_PREREQUISITE_INVALID",
    "SENTENCE_OUTPUT_INVALID",
    "SENTENCE_TIMEOUT",
    "SENTENCE_CANCELLED",
    "SENTENCE_QA_RESULT_NOT_FOUND",
    "SENTENCE_QA_RESULT_INVALID",
    "SENTENCE_QA_INDEX_INVALID",
    "SENTENCE_QA_STORAGE_INVALID",
    "SENTENCE_QA_OUTPUT_INVALID",
    "SENTENCE_INDEX_SOURCE_NOT_FOUND",
    "SENTENCE_INDEX_SOURCE_INVALID",
    "SENTENCE_INDEX_SOURCE_STALE",
    "SENTENCE_INDEX_STORAGE_INVALID",
    "SENTENCE_INDEX_OUTPUT_INVALID",
    "SENTENCE_INDEX_TIMEOUT",
    "SENTENCE_INDEX_CANCELLED",
    "RETRIEVAL_INDEX_NOT_FOUND",
    "RETRIEVAL_INDEX_INVALID",
    "RETRIEVAL_INDEX_STALE",
    "RETRIEVAL_STORAGE_INVALID",
    "RETRIEVAL_OUTPUT_INVALID",
    "RETRIEVAL_TIMEOUT",
    "RETRIEVAL_CANCELLED",
    "RERANK_RETRIEVAL_INVALID",
    "RERANK_SOURCE_INVALID",
    "RERANK_SOURCE_STALE",
    "RERANK_QA_STORAGE_INVALID",
    "RERANK_OUTPUT_INVALID",
    "RERANK_TIMEOUT",
    "RERANK_CANCELLED",
    "SLOT_INPUT_INVALID",
    "SLOT_SOURCE_INVALID",
    "SLOT_SOURCE_STALE",
    "SLOT_RETRIEVAL_INVALID",
    "SLOT_OUTPUT_INVALID",
    "SLOT_TIMEOUT",
    "SLOT_CANCELLED",
]


@dataclass(frozen=True)
class MediaErrorDefinition:
    message: str


ERRORS: Final[dict[str, MediaErrorDefinition]] = {
    "MEDIA_TOOL_UNAVAILABLE": MediaErrorDefinition("The configured media tool is unavailable."),
    "MEDIA_TOOL_TIMEOUT": MediaErrorDefinition("The media tool timed out."),
    "MEDIA_PROBE_PARSE_ERROR": MediaErrorDefinition("The media probe output was invalid."),
    "MEDIA_NOT_MEDIA": MediaErrorDefinition("The selected asset is not a valid media file."),
    "MEDIA_OUTPUT_INVALID": MediaErrorDefinition("The generated media output was invalid."),
    "MEDIA_CANCELLED": MediaErrorDefinition("The media operation was cancelled."),
    "TRANSCRIPTION_TOOL_UNAVAILABLE": MediaErrorDefinition("The local transcription tool is unavailable."),
    "TRANSCRIPTION_MODEL_UNAVAILABLE": MediaErrorDefinition("The local transcription model is unavailable."),
    "TRANSCRIPTION_OUTPUT_INVALID": MediaErrorDefinition("The local transcription output was invalid."),
    "TRANSCRIPTION_TIMEOUT": MediaErrorDefinition("The local transcription timed out."),
    "TRANSCRIPTION_CANCELLED": MediaErrorDefinition("The local transcription was cancelled."),
    "VAD_TOOL_UNAVAILABLE": MediaErrorDefinition("The local VAD backend is unavailable."),
    "VAD_OUTPUT_INVALID": MediaErrorDefinition("The local VAD output was invalid."),
    "VAD_TIMEOUT": MediaErrorDefinition("The local VAD timed out."),
    "VAD_CANCELLED": MediaErrorDefinition("The local VAD operation was cancelled."),
    "SENTENCE_PREREQUISITE_UNAVAILABLE": MediaErrorDefinition("The transcription or speech interval result is unavailable."),
    "SENTENCE_PREREQUISITE_INVALID": MediaErrorDefinition("The transcription or speech interval result is invalid."),
    "SENTENCE_OUTPUT_INVALID": MediaErrorDefinition("The sentence segmentation output was invalid."),
    "SENTENCE_TIMEOUT": MediaErrorDefinition("The sentence segmentation timed out."),
    "SENTENCE_CANCELLED": MediaErrorDefinition("The sentence segmentation was cancelled."),
    "SENTENCE_QA_RESULT_NOT_FOUND": MediaErrorDefinition("The requested B05 sentence result is unavailable."),
    "SENTENCE_QA_RESULT_INVALID": MediaErrorDefinition("The requested B05 sentence result is invalid."),
    "SENTENCE_QA_INDEX_INVALID": MediaErrorDefinition("The requested sentence index is invalid."),
    "SENTENCE_QA_STORAGE_INVALID": MediaErrorDefinition("The saved sentence QA markers are invalid."),
    "SENTENCE_QA_OUTPUT_INVALID": MediaErrorDefinition("The sentence QA output was invalid."),
    "SENTENCE_INDEX_SOURCE_NOT_FOUND": MediaErrorDefinition("The requested B05 sentence result is unavailable for indexing."),
    "SENTENCE_INDEX_SOURCE_INVALID": MediaErrorDefinition("The requested B05 sentence result is invalid for indexing."),
    "SENTENCE_INDEX_SOURCE_STALE": MediaErrorDefinition("The requested B05 sentence result is stale for the referenced asset."),
    "SENTENCE_INDEX_STORAGE_INVALID": MediaErrorDefinition("The sentence index storage is invalid."),
    "SENTENCE_INDEX_OUTPUT_INVALID": MediaErrorDefinition("The sentence index output was invalid."),
    "SENTENCE_INDEX_TIMEOUT": MediaErrorDefinition("The sentence index operation timed out."),
    "SENTENCE_INDEX_CANCELLED": MediaErrorDefinition("The sentence index operation was cancelled."),
    "RETRIEVAL_INDEX_NOT_FOUND": MediaErrorDefinition("A valid sentence index is unavailable for retrieval."),
    "RETRIEVAL_INDEX_INVALID": MediaErrorDefinition("The sentence index is invalid for retrieval."),
    "RETRIEVAL_INDEX_STALE": MediaErrorDefinition("The sentence index is stale for the referenced asset."),
    "RETRIEVAL_STORAGE_INVALID": MediaErrorDefinition("The sentence retrieval storage is invalid."),
    "RETRIEVAL_OUTPUT_INVALID": MediaErrorDefinition("The sentence retrieval output was invalid."),
    "RETRIEVAL_TIMEOUT": MediaErrorDefinition("The sentence retrieval operation timed out."),
    "RETRIEVAL_CANCELLED": MediaErrorDefinition("The sentence retrieval operation was cancelled."),
    "RERANK_RETRIEVAL_INVALID": MediaErrorDefinition("The B08 retrieval result is invalid for reranking."),
    "RERANK_SOURCE_INVALID": MediaErrorDefinition("The B05/B07 source is invalid for reranking."),
    "RERANK_SOURCE_STALE": MediaErrorDefinition("The B05/B07 source is stale for reranking."),
    "RERANK_QA_STORAGE_INVALID": MediaErrorDefinition("The B06 sentence QA storage is invalid."),
    "RERANK_OUTPUT_INVALID": MediaErrorDefinition("The sentence reranking output was invalid."),
    "RERANK_TIMEOUT": MediaErrorDefinition("The sentence reranking operation timed out."),
    "RERANK_CANCELLED": MediaErrorDefinition("The sentence reranking operation was cancelled."),
    "SLOT_INPUT_INVALID": MediaErrorDefinition("The information-slot input is invalid or exceeds its bounds."),
    "SLOT_SOURCE_INVALID": MediaErrorDefinition("The B08/B09 source is invalid for slot alignment."),
    "SLOT_SOURCE_STALE": MediaErrorDefinition("The B08/B09 source is stale for slot alignment."),
    "SLOT_RETRIEVAL_INVALID": MediaErrorDefinition("The B08/B09 retrieval result is invalid for slot alignment."),
    "SLOT_OUTPUT_INVALID": MediaErrorDefinition("The information-slot alignment output was invalid."),
    "SLOT_TIMEOUT": MediaErrorDefinition("The information-slot alignment operation timed out."),
    "SLOT_CANCELLED": MediaErrorDefinition("The information-slot alignment operation was cancelled."),
}


class MediaError(Exception):
    def __init__(self, code: MediaErrorCode, *, cause: BaseException | None = None) -> None:
        self.code = code if code in ERRORS else "MEDIA_OUTPUT_INVALID"
        self.cause = cause
        super().__init__(ERRORS[self.code].message)
