export const SCRIPT_STORYBOARD_SCHEMA_VERSION = 1 as const;
export const SCRIPT_STORYBOARD_CONTRACT_VERSION = "script-storyboard-v1" as const;
export const SCRIPT_STORYBOARD_PLANNER_VERSION = "deterministic-offline-script-storyboard-v1" as const;
export const SCRIPT_STORYBOARD_MIN_DURATION_MS = 1_000;
export const SCRIPT_STORYBOARD_MAX_DURATION_MS = 60_000;
export const SCRIPT_STORYBOARD_MAX_INPUT_BYTES = 160 * 1024;
export const SCRIPT_STORYBOARD_MAX_OUTPUT_BYTES = 160 * 1024;
export const SCRIPT_STORYBOARD_VISUAL_SOURCE_PRIORITY = ["user-material", "licensed-stock", "ai-image", "remotion-template", "text-card"] as const;
export type ScriptStoryboardVisualSource = (typeof SCRIPT_STORYBOARD_VISUAL_SOURCE_PRIORITY)[number];

type Role = "hook" | "body" | "cta";
type SlotKind = "hook" | "context" | "claim" | "evidence" | "benefit" | "requirement" | "process" | "cta" | "closing" | "other";
type PlanTimecode = Readonly<{ startMs: number; endMs: number }>;
type PlanSource = Readonly<{ sourceAssetId: string; sourceSentenceCacheKey: string; sentenceIndex: number; timecode: PlanTimecode; previewUri: string }>;
type PlanGap = Readonly<{ segmentId: string; slotId: string; role: Role; code: "alignment-gap" | "missing-narrative-role" | "duration-outside-tolerance"; detail: string }>;
type C02Segment = Readonly<{ segmentId: string; order: number; role: Role; slotId: string; slotKind: SlotKind; sourceText: string; status: "matched" | "gap"; candidateSentenceId: string | null; candidateRank: number | null; sentenceText: string | null; source: PlanSource | null; durationMs: number; selectionReason: string | null; gapReason: PlanGap | null }>;
export type ScriptStoryboardNarrativePlan = Readonly<{ schemaVersion: 1; planVersion: "narrative-remix-plan-v1"; inputVersion: "deterministic-narrative-input-v1"; projectId: string; theme: string; audience: string; outline: string | null; targetDurationMs: number; toleranceLowerMs: number; toleranceUpperMs: number; selectedDurationMs: number; durationStatus: "within-tolerance" | "outside-tolerance"; status: "ready" | "gaps" | "needs-duration-optimization"; selectionPolicy: "b10-first-complete-candidate-v1"; alignmentVersion: "information-slot-alignment-v1"; planDigest: string; segments: readonly C02Segment[]; gaps: readonly PlanGap[] }>;
type C03Segment = Readonly<C02Segment & { operation: "keep" | "replace" | "add" }>;
export type ScriptStoryboardDurationPlan = Readonly<{ schemaVersion: 1; optimizationVersion: "duration-optimization-v1"; projectId: string; sourcePlanDigest: string; targetDurationMs: number; toleranceLowerMs: number; toleranceUpperMs: number; selectedDurationMs: number; durationStatus: "within-tolerance" | "outside-tolerance"; status: "optimized" | "unchanged" | "gaps" | "needs-duration-optimization"; selectionPolicy: "bounded-whole-sentence-knapsack-v1"; segments: readonly C03Segment[]; changes: readonly Record<string, unknown>[]; gaps: readonly PlanGap[] }>;

export type ScriptStoryboardBrief = Readonly<{ theme: string; audience: string; objective: string; language: "zh-CN" }>;
export type ScriptStoryboardTarget = Readonly<{ platform: "douyin"; aspectRatio: "9:16"; durationMs: number; tolerancePercent: 20 }>;
export type ScriptStoryboardVisualContext = Readonly<{ hasUserMaterial: boolean }>;
export type ScriptStoryboardProvenance = Readonly<{ id: string; kind: "user-brief" | "source-record" | "c02-segment" | "c03-selection"; label: string; sourceSegmentId?: string; verified: boolean }>;
export type ScriptStoryboardFact = Readonly<{ id: string; field: "jobTitle" | "salary" | "location" | "benefit" | "qualification" | "workContent" | "other"; value: string; provenanceIds: readonly string[]; verification: "verified" | "unverified" | "needs-user-confirmation" }>;
export type ScriptStoryboardFactBinding = Readonly<{ segmentId: string; factIds: readonly string[] }>;
export type ScriptStoryboardInput = Readonly<{ schemaVersion: 1; contractVersion: typeof SCRIPT_STORYBOARD_CONTRACT_VERSION; projectId: string; brief: ScriptStoryboardBrief; facts: readonly ScriptStoryboardFact[]; forbiddenInferences: readonly string[]; target: ScriptStoryboardTarget; visualContext: ScriptStoryboardVisualContext; provenance: readonly ScriptStoryboardProvenance[]; factBindings: readonly ScriptStoryboardFactBinding[]; sourcePlan: ScriptStoryboardNarrativePlan; durationPlan?: ScriptStoryboardDurationPlan | null }>;

export type ScriptStoryboardSegment = Readonly<{ segmentId: string; sourceSegmentId: string; order: number; role: Role; status: "matched" | "gap"; sentenceId: string | null; text: string | null; source: PlanSource | null; durationMs: number; provenanceIds: readonly string[]; factIds: readonly string[]; confirmation: "not-required" | "verified" | "needs-user-confirmation" }>;
export type ScriptStoryboardShot = Readonly<{ shotId: string; order: number; segmentId: string; durationMs: number; visualSourcePriority: readonly ScriptStoryboardVisualSource[]; fallbackReason: "planned" | "no-user-material" | "source-gap"; visualIntent: string }>;
export type ScriptStoryboardFactAudit = Readonly<{ factId: string; status: "bound" | "unbound" | "needs-user-confirmation"; provenanceIds: readonly string[]; segmentIds: readonly string[] }>;
export type ScriptStoryboardResult = Readonly<{ schemaVersion: 1; contractVersion: typeof SCRIPT_STORYBOARD_CONTRACT_VERSION; plannerVersion: typeof SCRIPT_STORYBOARD_PLANNER_VERSION; projectId: string; sourcePlanDigest: string; durationPlanSourceDigest: string | null; targetDurationMs: number; toleranceLowerMs: number; toleranceUpperMs: number; selectedDurationMs: number; durationStatus: "within-tolerance" | "outside-tolerance"; durationPolicy: "c02-complete-sentence-v1" | "c03-bounded-whole-sentence-knapsack-v1"; status: "ready" | "gaps" | "needs-user-confirmation" | "needs-duration-optimization"; brief: ScriptStoryboardBrief; forbiddenInferences: readonly string[]; provenance: readonly ScriptStoryboardProvenance[]; facts: readonly ScriptStoryboardFactAudit[]; script: Readonly<{ hook: ScriptStoryboardSegment; body: readonly ScriptStoryboardSegment[]; cta: ScriptStoryboardSegment }>; shots: readonly ScriptStoryboardShot[] }>;

export type ScriptStoryboardValidationError = Readonly<{ path: string; message: string }>;
export class ScriptStoryboardValidationException extends Error {
  readonly errors: readonly ScriptStoryboardValidationError[];
  constructor(errors: readonly ScriptStoryboardValidationError[]) { super(errors.map((item) => `${item.path}: ${item.message}`).join("; ")); this.name = "ScriptStoryboardValidationException"; this.errors = errors; }
}

export function isScriptStoryboardInput(value: unknown): value is ScriptStoryboardInput { try { validateScriptStoryboardInput(value); return true; } catch { return false; } }
export function isScriptStoryboardResult(value: unknown): value is ScriptStoryboardResult { try { validateScriptStoryboardResult(value); return true; } catch { return false; } }

export function validateScriptStoryboardInput(value: unknown): ScriptStoryboardInput {
  const errors: ScriptStoryboardValidationError[] = [];
  const input = record(value, "$", errors);
  if (!input) throw new ScriptStoryboardValidationException(errors);
  only(input, ["schemaVersion", "contractVersion", "projectId", "brief", "facts", "forbiddenInferences", "target", "visualContext", "provenance", "factBindings", "sourcePlan", "durationPlan"], "$", errors);
  if (input.schemaVersion !== 1) add(errors, "$.schemaVersion", "must be 1");
  if (input.contractVersion !== SCRIPT_STORYBOARD_CONTRACT_VERSION) add(errors, "$.contractVersion", "must be script-storyboard-v1");
  checkUuid(input.projectId, "$.projectId", errors);
  const brief = validateBrief(input.brief, "$.brief", errors);
  const target = validateTarget(input.target, "$.target", errors);
  const visualContext = validateVisualContext(input.visualContext, "$.visualContext", errors);
  const provenance = validateProvenanceList(input.provenance, "$.provenance", errors);
  const facts = validateFacts(input.facts, "$.facts", provenance, errors);
  const plan = validateNarrativePlan(input.sourcePlan, "$.sourcePlan", errors);
  validateFactBindings(input.factBindings, "$.factBindings", facts, plan, errors);
  if (input.durationPlan !== undefined && input.durationPlan !== null) validateDurationPlan(input.durationPlan, "$.durationPlan", plan, errors);
  if (target && plan && target.durationMs !== plan.targetDurationMs) add(errors, "$.target.durationMs", "must match sourcePlan.targetDurationMs");
  rejectForbidden(value, "$", errors);
  if (!boundedJson(value, SCRIPT_STORYBOARD_MAX_INPUT_BYTES)) add(errors, "$", "exceeds D05 input size limit");
  if (errors.length) throw new ScriptStoryboardValidationException(errors);
  return value as ScriptStoryboardInput;
}

export function validateScriptStoryboardResult(value: unknown): ScriptStoryboardResult {
  const errors: ScriptStoryboardValidationError[] = [];
  const result = record(value, "$", errors);
  if (!result) throw new ScriptStoryboardValidationException(errors);
  only(result, ["schemaVersion", "contractVersion", "plannerVersion", "projectId", "sourcePlanDigest", "durationPlanSourceDigest", "targetDurationMs", "toleranceLowerMs", "toleranceUpperMs", "selectedDurationMs", "durationStatus", "durationPolicy", "status", "brief", "forbiddenInferences", "provenance", "facts", "script", "shots"], "$", errors);
  if (result.schemaVersion !== 1 || result.contractVersion !== SCRIPT_STORYBOARD_CONTRACT_VERSION || result.plannerVersion !== SCRIPT_STORYBOARD_PLANNER_VERSION) add(errors, "$", "has an invalid D05 version");
  checkUuid(result.projectId, "$.projectId", errors);
  checkDigest(result.sourcePlanDigest, "$.sourcePlanDigest", errors);
  if (result.durationPlanSourceDigest !== null) checkDigest(result.durationPlanSourceDigest, "$.durationPlanSourceDigest", errors);
  checkInteger(result.targetDurationMs, SCRIPT_STORYBOARD_MIN_DURATION_MS, SCRIPT_STORYBOARD_MAX_DURATION_MS, "$.targetDurationMs", errors);
  checkInteger(result.toleranceLowerMs, 800, SCRIPT_STORYBOARD_MAX_DURATION_MS, "$.toleranceLowerMs", errors);
  checkInteger(result.toleranceUpperMs, 800, 72_000, "$.toleranceUpperMs", errors);
  checkInteger(result.selectedDurationMs, 0, SCRIPT_STORYBOARD_MAX_DURATION_MS, "$.selectedDurationMs", errors);
  const brief = validateBrief(result.brief, "$.brief", errors);
  validateTextArray(result.forbiddenInferences, "$.forbiddenInferences", 32, 512, errors);
  const provenance = validateProvenanceList(result.provenance, "$.provenance", errors);
  const facts = validateFactAudits(result.facts, "$.facts", provenance, errors);
  const script = validateScript(result.script, "$.script", provenance, facts, errors);
  const shots = validateShots(result.shots, "$.shots", script, errors);
  if (result.toleranceLowerMs !== Math.floor(Number(result.targetDurationMs) * 0.8) || result.toleranceUpperMs !== Math.floor(Number(result.targetDurationMs) * 1.2)) add(errors, "$", "duration tolerance does not match target");
  if (script) {
    const segments = [script.hook, ...script.body, script.cta];
    const duration = segments.reduce((sum, item) => sum + item.durationMs, 0);
    if (result.selectedDurationMs !== duration) add(errors, "$.selectedDurationMs", "must equal script segment duration sum");
    if (result.durationStatus !== (result.toleranceLowerMs <= duration && duration <= result.toleranceUpperMs ? "within-tolerance" : "outside-tolerance")) add(errors, "$.durationStatus", "does not match selected duration");
    const first = segments[0];
    const last = segments[segments.length - 1];
    if (!first || !last || first.role !== "hook" || last.role !== "cta" || segments.slice(1, -1).some((item) => item.role !== "body")) add(errors, "$.script", "must be hook/body/CTA ordered");
    if (shots && (shots.length !== segments.length || shots.some((shot, index) => { const segment = segments[index]; return !segment || shot.segmentId !== segment.segmentId || shot.durationMs !== segment.durationMs; }))) add(errors, "$.shots", "must map one-to-one to script segments");
  }
  if (brief && result.projectId.length === 0) add(errors, "$.brief", "must be bound to a project");
  rejectForbidden(value, "$", errors);
  if (!boundedJson(value, SCRIPT_STORYBOARD_MAX_OUTPUT_BYTES)) add(errors, "$", "exceeds D05 output size limit");
  if (errors.length) throw new ScriptStoryboardValidationException(errors);
  return value as ScriptStoryboardResult;
}

function validateBrief(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): ScriptStoryboardBrief | undefined {
  const item = record(value, path, errors); if (!item) return undefined;
  only(item, ["theme", "audience", "objective", "language"], path, errors);
  for (const key of ["theme", "audience", "objective"] as const) checkText(item[key], `${path}.${key}`, errors, key === "objective" ? 512 : 256);
  if (item.language !== "zh-CN") add(errors, `${path}.language`, "must be zh-CN");
  return typeof item.theme === "string" && typeof item.audience === "string" && typeof item.objective === "string" ? item as ScriptStoryboardBrief : undefined;
}
function validateTarget(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): ScriptStoryboardTarget | undefined {
  const item = record(value, path, errors); if (!item) return undefined;
  only(item, ["platform", "aspectRatio", "durationMs", "tolerancePercent"], path, errors);
  if (item.platform !== "douyin") add(errors, `${path}.platform`, "must be douyin");
  if (item.aspectRatio !== "9:16") add(errors, `${path}.aspectRatio`, "must be 9:16");
  checkInteger(item.durationMs, SCRIPT_STORYBOARD_MIN_DURATION_MS, SCRIPT_STORYBOARD_MAX_DURATION_MS, `${path}.durationMs`, errors);
  if (item.tolerancePercent !== 20) add(errors, `${path}.tolerancePercent`, "must be 20");
  return item as ScriptStoryboardTarget;
}
function validateVisualContext(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): ScriptStoryboardVisualContext | undefined { const item = record(value, path, errors); if (!item) return undefined; only(item, ["hasUserMaterial"], path, errors); if (typeof item.hasUserMaterial !== "boolean") add(errors, `${path}.hasUserMaterial`, "must be boolean"); return item as ScriptStoryboardVisualContext; }
function validateProvenanceList(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): Map<string, ScriptStoryboardProvenance> {
  const values = array(value, 128, path, errors); const result = new Map<string, ScriptStoryboardProvenance>();
  values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["id", "kind", "label", "sourceSegmentId", "verified"], `${path}[${index}]`, errors); checkId(item.id, `${path}[${index}].id`, errors); checkText(item.label, `${path}[${index}].label`, errors, 160); if (item.sourceSegmentId !== undefined) checkId(item.sourceSegmentId, `${path}[${index}].sourceSegmentId`, errors); if (!["user-brief", "source-record", "c02-segment", "c03-selection"].includes(String(item.kind))) add(errors, `${path}[${index}].kind`, "is not allowed"); if (typeof item.verified !== "boolean") add(errors, `${path}[${index}].verified`, "must be boolean"); if ((item.kind === "c02-segment" || item.kind === "c03-selection") && typeof item.sourceSegmentId !== "string") add(errors, `${path}[${index}].sourceSegmentId`, "is required for source provenance"); if (typeof item.id === "string") { if (result.has(item.id)) add(errors, path, "contains duplicate provenance ids"); result.set(item.id, item as ScriptStoryboardProvenance); } });
  return result;
}
function validateFacts(value: unknown, path: string, provenance: Map<string, ScriptStoryboardProvenance>, errors: ScriptStoryboardValidationError[]): Map<string, ScriptStoryboardFact> { const values = array(value, 64, path, errors); const result = new Map<string, ScriptStoryboardFact>(); values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["id", "field", "value", "provenanceIds", "verification"], `${path}[${index}]`, errors); checkId(item.id, `${path}[${index}].id`, errors); checkText(item.value, `${path}[${index}].value`, errors, 256); validateIdArray(item.provenanceIds, `${path}[${index}].provenanceIds`, 8, errors, provenance); if (!["jobTitle", "salary", "location", "benefit", "qualification", "workContent", "other"].includes(String(item.field))) add(errors, `${path}[${index}].field`, "is not allowed"); if (!["verified", "unverified", "needs-user-confirmation"].includes(String(item.verification))) add(errors, `${path}[${index}].verification`, "is not allowed"); if (typeof item.id === "string") { if (result.has(item.id)) add(errors, path, "contains duplicate fact ids"); result.set(item.id, item as ScriptStoryboardFact); } }); return result; }

function validateNarrativePlan(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): ScriptStoryboardNarrativePlan | undefined {
  const plan = record(value, path, errors); if (!plan) return undefined;
  only(plan, ["schemaVersion", "planVersion", "inputVersion", "projectId", "theme", "audience", "outline", "targetDurationMs", "toleranceLowerMs", "toleranceUpperMs", "selectedDurationMs", "durationStatus", "status", "selectionPolicy", "alignmentVersion", "planDigest", "segments", "gaps"], path, errors);
  if (plan.schemaVersion !== 1 || plan.planVersion !== "narrative-remix-plan-v1" || plan.inputVersion !== "deterministic-narrative-input-v1") add(errors, path, "is not a C02 narrative plan v1");
  checkUuid(plan.projectId, `${path}.projectId`, errors); checkDigest(plan.planDigest, `${path}.planDigest`, errors); checkInteger(plan.targetDurationMs, 1_000, 600_000, `${path}.targetDurationMs`, errors); checkInteger(plan.selectedDurationMs, 0, 86_400_000, `${path}.selectedDurationMs`, errors); checkText(plan.theme, `${path}.theme`, errors, 512); checkText(plan.audience, `${path}.audience`, errors, 256); if (plan.outline !== null) checkText(plan.outline, `${path}.outline`, errors, 8192, true);
  const segments = array(plan.segments, 32, `${path}.segments`, errors); const ids = new Set<string>(); let total = 0; segments?.forEach((raw, index) => { const item = validateC02Segment(raw, `${path}.segments[${index}]`, errors); if (item) { if (ids.has(item.segmentId)) add(errors, `${path}.segments`, "contains duplicate segment ids"); ids.add(item.segmentId); total += item.durationMs; } }); validateGaps(plan.gaps, `${path}.gaps`, errors); if (plan.selectedDurationMs !== total) add(errors, `${path}.selectedDurationMs`, "does not match C02 segment duration sum"); if (plan.toleranceLowerMs !== Math.floor(Number(plan.targetDurationMs) * .8) || plan.toleranceUpperMs !== Math.floor(Number(plan.targetDurationMs) * 1.2)) add(errors, path, "has invalid C02 tolerance"); return plan as ScriptStoryboardNarrativePlan;
}
function validateC02Segment(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): C02Segment | undefined { const item = record(value, path, errors); if (!item) return undefined; only(item, ["segmentId", "order", "role", "slotId", "slotKind", "sourceText", "status", "candidateSentenceId", "candidateRank", "sentenceText", "source", "durationMs", "selectionReason", "gapReason"], path, errors); checkId(item.segmentId, `${path}.segmentId`, errors); checkInteger(item.order, 1, 32, `${path}.order`, errors); checkId(item.slotId, `${path}.slotId`, errors); checkText(item.sourceText, `${path}.sourceText`, errors, 512); checkInteger(item.durationMs, 0, 86_400_000, `${path}.durationMs`, errors); if (!["hook", "body", "cta"].includes(String(item.role))) add(errors, `${path}.role`, "is not allowed"); if (!["matched", "gap"].includes(String(item.status))) add(errors, `${path}.status`, "is not allowed"); if (item.status === "matched") { checkDigest(item.candidateSentenceId, `${path}.candidateSentenceId`, errors); checkText(item.sentenceText, `${path}.sentenceText`, errors, 512); validateSource(item.source, `${path}.source`, errors); if (!Number.isInteger(item.candidateRank) || item.candidateRank !== 1) add(errors, `${path}.candidateRank`, "must be rank 1"); if (item.durationMs !== sourceDuration(item.source)) add(errors, `${path}.durationMs`, "must equal source timecode duration"); if (item.gapReason !== null) add(errors, `${path}.gapReason`, "must be null for matched segment"); } else { if (item.candidateSentenceId !== null || item.sentenceText !== null || item.source !== null || item.durationMs !== 0 || item.gapReason === null) add(errors, path, "has invalid C02 gap accounting"); } return item as C02Segment; }
function validateSource(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { const item = record(value, path, errors); if (!item) return; only(item, ["sourceAssetId", "sourceSentenceCacheKey", "sentenceIndex", "timecode", "previewUri"], path, errors); checkUuid(item.sourceAssetId, `${path}.sourceAssetId`, errors); checkDigest(item.sourceSentenceCacheKey, `${path}.sourceSentenceCacheKey`, errors); checkInteger(item.sentenceIndex, 0, 1999, `${path}.sentenceIndex`, errors); const tc = record(item.timecode, `${path}.timecode`, errors); if (tc) { only(tc, ["startMs", "endMs"], `${path}.timecode`, errors); checkInteger(tc.startMs, 0, 86_400_000, `${path}.timecode.startMs`, errors); checkInteger(tc.endMs, 1, 86_400_000, `${path}.timecode.endMs`, errors); if (!(Number(tc.endMs) > Number(tc.startMs))) add(errors, `${path}.timecode`, "must have positive duration"); } const expected = typeof item.sourceAssetId === "string" && tc ? `supervideo://asset/${item.sourceAssetId}?kind=audio&startMs=${tc.startMs}&endMs=${tc.endMs}` : ""; if (item.previewUri !== expected) add(errors, `${path}.previewUri`, "must be the controlled C02 preview URI"); }
function sourceDuration(value: unknown): number { const item = value as { timecode?: { startMs?: number; endMs?: number } }; return Number(item.timecode?.endMs) - Number(item.timecode?.startMs); }
function validateGaps(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { const values = array(value, 33, path, errors); values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["segmentId", "slotId", "role", "code", "detail"], `${path}[${index}]`, errors); checkId(item.segmentId, `${path}[${index}].segmentId`, errors); checkId(item.slotId, `${path}[${index}].slotId`, errors); checkText(item.detail, `${path}[${index}].detail`, errors, 160); if (!["hook", "body", "cta"].includes(String(item.role)) || !["alignment-gap", "missing-narrative-role", "duration-outside-tolerance"].includes(String(item.code))) add(errors, `${path}[${index}]`, "has an invalid gap enum"); }); }
function validateChanges(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { const values = array(value, 64, path, errors); values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["segmentId", "slotId", "role", "operation", "before", "after", "selectionReason"], `${path}[${index}]`, errors); checkId(item.segmentId, `${path}[${index}].segmentId`, errors); checkId(item.slotId, `${path}[${index}].slotId`, errors); checkText(item.selectionReason, `${path}[${index}].selectionReason`, errors, 160); if (!["hook", "body", "cta"].includes(String(item.role)) || !["keep", "replace", "add", "remove"].includes(String(item.operation))) add(errors, `${path}[${index}]`, "has an invalid C03 change enum"); if (item.before !== null && item.before !== undefined) validateDurationSentence(item.before, `${path}[${index}].before`, errors); if (item.after !== null && item.after !== undefined) validateDurationSentence(item.after, `${path}[${index}].after`, errors); }); }
function validateDurationSentence(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { const item = record(value, path, errors); if (!item) return; only(item, ["sentenceId", "sentenceText", "source", "durationMs", "candidateRank"], path, errors); checkDigest(item.sentenceId, `${path}.sentenceId`, errors); checkText(item.sentenceText, `${path}.sentenceText`, errors, 512); validateSource(item.source, `${path}.source`, errors); checkInteger(item.durationMs, 1, 86_400_000, `${path}.durationMs`, errors); if (!Number.isInteger(item.candidateRank) || item.candidateRank < 1 || item.candidateRank > 8) add(errors, `${path}.candidateRank`, "must be between 1 and 8"); if (item.durationMs !== sourceDuration(item.source)) add(errors, `${path}.durationMs`, "must equal source duration"); }
function validateFactBindings(value: unknown, path: string, facts: Map<string, ScriptStoryboardFact>, plan: ScriptStoryboardNarrativePlan | undefined, errors: ScriptStoryboardValidationError[]): void { const values = array(value, 32, path, errors); const segmentIds = new Set(plan?.segments.map((item) => item.segmentId) ?? []); values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["segmentId", "factIds"], `${path}[${index}]`, errors); checkId(item.segmentId, `${path}[${index}].segmentId`, errors); if (!segmentIds.has(String(item.segmentId))) add(errors, `${path}[${index}].segmentId`, "must reference sourcePlan segment"); validateIdArray(item.factIds, `${path}[${index}].factIds`, 16, errors, facts); }); }
function validateDurationPlan(value: unknown, path: string, plan: ScriptStoryboardNarrativePlan | undefined, errors: ScriptStoryboardValidationError[]): void { const item = record(value, path, errors); if (!item) return; only(item, ["schemaVersion", "optimizationVersion", "projectId", "sourcePlanDigest", "targetDurationMs", "toleranceLowerMs", "toleranceUpperMs", "selectedDurationMs", "durationStatus", "status", "selectionPolicy", "segments", "changes", "gaps"], path, errors); if (item.schemaVersion !== 1 || item.optimizationVersion !== "duration-optimization-v1" || item.selectionPolicy !== "bounded-whole-sentence-knapsack-v1") add(errors, path, "is not a C03 duration plan v1"); checkUuid(item.projectId, `${path}.projectId`, errors); checkDigest(item.sourcePlanDigest, `${path}.sourcePlanDigest`, errors); if (plan && item.sourcePlanDigest !== plan.planDigest) add(errors, `${path}.sourcePlanDigest`, "must match sourcePlan.planDigest"); if (plan && item.projectId !== plan.projectId) add(errors, `${path}.projectId`, "must match sourcePlan.projectId"); if (plan && item.targetDurationMs !== plan.targetDurationMs) add(errors, `${path}.targetDurationMs`, "must match sourcePlan.targetDurationMs"); const segments = array(item.segments, 32, `${path}.segments`, errors); let total = 0; segments?.forEach((raw, index) => { const segment = record(raw, `${path}.segments[${index}]`, errors); if (!segment) return; only(segment, ["segmentId", "order", "role", "slotId", "slotKind", "sourceText", "status", "operation", "candidateSentenceId", "candidateRank", "sentenceText", "source", "durationMs", "selectionReason", "gapReason"], `${path}.segments[${index}]`, errors); checkId(segment.segmentId, `${path}.segments[${index}].segmentId`, errors); if (!["hook", "body", "cta"].includes(String(segment.role)) || !["matched", "gap"].includes(String(segment.status)) || !["keep", "replace", "add"].includes(String(segment.operation))) add(errors, `${path}.segments[${index}]`, "has an invalid C03 segment enum"); if (segment.status === "matched") { validateSource(segment.source, `${path}.segments[${index}].source`, errors); checkDigest(segment.candidateSentenceId, `${path}.segments[${index}].candidateSentenceId`, errors); checkText(segment.sentenceText, `${path}.segments[${index}].sentenceText`, errors, 512); total += Number(segment.durationMs); } }); validateChanges(item.changes, `${path}.changes`, errors); validateGaps(item.gaps, `${path}.gaps`, errors); if (item.selectedDurationMs !== total) add(errors, `${path}.selectedDurationMs`, "does not match C03 segment duration sum"); }
function validateScript(value: unknown, path: string, provenance: Map<string, ScriptStoryboardProvenance>, facts: Map<string, ScriptStoryboardFactAudit>, errors: ScriptStoryboardValidationError[]): { hook: ScriptStoryboardSegment; body: ScriptStoryboardSegment[]; cta: ScriptStoryboardSegment } | undefined { const item = record(value, path, errors); if (!item) return undefined; only(item, ["hook", "body", "cta"], path, errors); const hook = validateOutputSegment(item.hook, `${path}.hook`, provenance, facts, errors); const bodyValues = array(item.body, 32, `${path}.body`, errors); const body = bodyValues?.map((raw, index) => validateOutputSegment(raw, `${path}.body[${index}]`, provenance, facts, errors)).filter((item): item is ScriptStoryboardSegment => item !== undefined) ?? []; const cta = validateOutputSegment(item.cta, `${path}.cta`, provenance, facts, errors); if (!hook || !cta) return undefined; return { hook, body, cta }; }
function validateOutputSegment(value: unknown, path: string, provenance: Map<string, ScriptStoryboardProvenance>, facts: Map<string, ScriptStoryboardFactAudit>, errors: ScriptStoryboardValidationError[]): ScriptStoryboardSegment | undefined { const item = record(value, path, errors); if (!item) return undefined; only(item, ["segmentId", "sourceSegmentId", "order", "role", "status", "sentenceId", "text", "source", "durationMs", "provenanceIds", "factIds", "confirmation"], path, errors); checkId(item.segmentId, `${path}.segmentId`, errors); checkId(item.sourceSegmentId, `${path}.sourceSegmentId`, errors); checkInteger(item.order, 1, 32, `${path}.order`, errors); checkInteger(item.durationMs, 0, SCRIPT_STORYBOARD_MAX_DURATION_MS, `${path}.durationMs`, errors); validateIdArray(item.provenanceIds, `${path}.provenanceIds`, 16, errors, provenance); validateIdArray(item.factIds, `${path}.factIds`, 16, errors, facts); if (!["hook", "body", "cta"].includes(String(item.role)) || !["matched", "gap"].includes(String(item.status)) || !["not-required", "verified", "needs-user-confirmation"].includes(String(item.confirmation))) add(errors, path, "has an invalid storyboard segment enum"); if (item.status === "matched") { checkDigest(item.sentenceId, `${path}.sentenceId`, errors); checkText(item.text, `${path}.text`, errors, 512); validateSource(item.source, `${path}.source`, errors); if (item.durationMs !== sourceDuration(item.source)) add(errors, `${path}.durationMs`, "must equal complete sentence source duration"); } else if (item.sentenceId !== null || item.text !== null || item.source !== null || item.durationMs !== 0) add(errors, path, "gap segment cannot contain sentence or duration"); return item as ScriptStoryboardSegment; }
function validateFactAudits(value: unknown, path: string, provenance: Map<string, ScriptStoryboardProvenance>, errors: ScriptStoryboardValidationError[]): Map<string, ScriptStoryboardFactAudit> { const values = array(value, 64, path, errors); const result = new Map<string, ScriptStoryboardFactAudit>(); values?.forEach((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return; only(item, ["factId", "status", "provenanceIds", "segmentIds"], `${path}[${index}]`, errors); checkId(item.factId, `${path}[${index}].factId`, errors); validateIdArray(item.provenanceIds, `${path}[${index}].provenanceIds`, 8, errors, provenance); validateIdArray(item.segmentIds, `${path}[${index}].segmentIds`, 32, errors); if (!["bound", "unbound", "needs-user-confirmation"].includes(String(item.status))) add(errors, `${path}[${index}].status`, "is not allowed"); if (typeof item.factId === "string") result.set(item.factId, item as ScriptStoryboardFactAudit); }); return result; }
function validateShots(value: unknown, path: string, script: { hook: ScriptStoryboardSegment; body: ScriptStoryboardSegment[]; cta: ScriptStoryboardSegment } | undefined, errors: ScriptStoryboardValidationError[]): ScriptStoryboardShot[] | undefined { const values = array(value, 32, path, errors); return values?.map((raw, index) => { const item = record(raw, `${path}[${index}]`, errors); if (!item) return undefined; only(item, ["shotId", "order", "segmentId", "durationMs", "visualSourcePriority", "fallbackReason", "visualIntent"], `${path}[${index}]`, errors); checkId(item.shotId, `${path}[${index}].shotId`, errors); checkId(item.segmentId, `${path}[${index}].segmentId`, errors); checkInteger(item.order, 1, 32, `${path}[${index}].order`, errors); checkInteger(item.durationMs, 0, SCRIPT_STORYBOARD_MAX_DURATION_MS, `${path}[${index}].durationMs`, errors); const priority = array(item.visualSourcePriority, 5, `${path}[${index}].visualSourcePriority`, errors); if (!priority || priority.length === 0) add(errors, `${path}[${index}].visualSourcePriority`, "must not be empty"); if (priority && new Set(priority.map(String)).size !== priority.length) add(errors, `${path}[${index}].visualSourcePriority`, "must not contain duplicates"); priority?.forEach((source, sourceIndex) => { if (!(SCRIPT_STORYBOARD_VISUAL_SOURCE_PRIORITY as readonly unknown[]).includes(source)) add(errors, `${path}[${index}].visualSourcePriority[${sourceIndex}]`, "is not in the fixed allowlist"); }); if (!["planned", "no-user-material", "source-gap"].includes(String(item.fallbackReason))) add(errors, `${path}[${index}].fallbackReason`, "is not allowed"); checkText(item.visualIntent, `${path}[${index}].visualIntent`, errors, 160); return item as ScriptStoryboardShot; }).filter((item): item is ScriptStoryboardShot => item !== undefined); }

function validateIdArray(value: unknown, path: string, max: number, errors: ScriptStoryboardValidationError[], refs?: Map<string, unknown>): void { const items = array(value, max, path, errors); if (!items) return; if (items.length !== new Set(items.map(String)).size) add(errors, path, "must not contain duplicates"); items.forEach((item, index) => { checkId(item, `${path}[${index}]`, errors); if (refs && typeof item === "string" && !refs.has(item)) add(errors, `${path}[${index}]`, "must reference a declared identifier"); }); }
function validateTextArray(value: unknown, path: string, maxItems: number, maxText: number, errors: ScriptStoryboardValidationError[]): void { const items = array(value, maxItems, path, errors); items?.forEach((item, index) => checkText(item, `${path}[${index}]`, errors, maxText)); }
function record(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): Record<string, any> | undefined { if (!value || typeof value !== "object" || Array.isArray(value)) { add(errors, path, "must be an object"); return undefined; } return value as Record<string, any>; }
function array(value: unknown, max: number, path: string, errors: ScriptStoryboardValidationError[]): any[] | undefined { if (!Array.isArray(value)) { add(errors, path, "must be an array"); return undefined; } if (value.length > max) add(errors, path, `must contain at most ${max} items`); return value; }
function only(value: Record<string, any>, keys: readonly string[], path: string, errors: ScriptStoryboardValidationError[]): void { const allowed = new Set(keys); for (const key of Object.keys(value)) if (!allowed.has(key)) add(errors, `${path}.${key}`, "unknown key"); }
function add(errors: ScriptStoryboardValidationError[], path: string, message: string): void { errors.push({ path, message }); }
function checkId(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,95}$/.test(value)) add(errors, path, "must be a bounded identifier"); }
function checkUuid(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value)) add(errors, path, "must be a UUID"); }
function checkDigest(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { if (typeof value !== "string" || !/^[0-9a-f]{64}$/.test(value)) add(errors, path, "must be a SHA-256 digest"); }
function checkInteger(value: unknown, min: number, max: number, path: string, errors: ScriptStoryboardValidationError[]): void { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < min || value > max) add(errors, path, `must be an integer between ${min} and ${max}`); }
function checkText(value: unknown, path: string, errors: ScriptStoryboardValidationError[], max = 512, allowNewlines = false): void { if (typeof value !== "string" || value.trim().length === 0 || value.length > max || (allowNewlines ? /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/ : /[\u0000-\u001f]/).test(value) || /(?:^[A-Za-z]:[\\/]|^\\\\|^\/|sk-[A-Za-z0-9]{16,}|(?:api[_-]?key|access[_-]?token|bearer)\s*[:=]|https?:\/\/)/i.test(value)) add(errors, path, "must be bounded text without path or secret"); }
function boundedJson(value: unknown, maxBytes: number): boolean { try { return new TextEncoder().encode(JSON.stringify(value)).length <= maxBytes; } catch { return false; } }
function rejectForbidden(value: unknown, path: string, errors: ScriptStoryboardValidationError[]): void { if (Array.isArray(value)) value.forEach((item, index) => rejectForbidden(item, `${path}[${index}]`, errors)); else if (value && typeof value === "object") Object.entries(value).forEach(([key, item]) => { const normalized = key.toLowerCase().replace(/[^a-z0-9]/g, ""); if (["secret", "token", "credentialref", "credential", "apikey", "password", "command", "path", "provider", "prompt", "authorization", "bearer"].includes(normalized)) add(errors, `${path}.${key}`, "forbidden key"); rejectForbidden(item, `${path}.${key}`, errors); }); else if (typeof value === "string" && /(?:^[A-Za-z]:[\\/]|^\\\\|^\/|sk-[A-Za-z0-9]{16,}|(?:api[_-]?key|access[_-]?token|bearer)\s*[:=]|https?:\/\/)/i.test(value)) add(errors, path, "forbidden path or secret"); }
