"""SQLite storage foundation for one SuperVideo project database."""

from .database import DATABASE_BUSY_TIMEOUT_MS, Database, IntegrityReport
from .errors import ERRORS, StorageError, StorageErrorCode
from .migrations import (
    DATABASE_SCHEMA_VERSION,
    Migration,
    MigrationReport,
    MigrationRunner,
    discover_migrations,
    migration_checksum,
    normalize_migration_text,
)
from .models import (
    Asset,
    AssetCreate,
    AssetRecord,
    Job,
    JobCreate,
    JobEventCreate,
    JobEventRecord,
    JobRecord,
    Message,
    MessageCreate,
    MessageRecord,
    Project,
    ProjectCreate,
    ProjectRecord,
    ResearchSearchRecord,
    SourceRecord,
    TimelineVersion,
    TimelineVersionCreate,
    TimelineVersionRecord,
    deserialize_json_value,
    new_id,
    serialize_json_value,
    utc_now_ms,
)
from .repositories import (
    AssetRepository,
    JobRepository,
    MessageRepository,
    ProjectRepository,
    ResearchRepository,
    TimelineVersionRepository,
)

__all__ = [
    "Asset",
    "AssetCreate",
    "AssetRecord",
    "AssetRepository",
    "DATABASE_BUSY_TIMEOUT_MS",
    "DATABASE_SCHEMA_VERSION",
    "Database",
    "ERRORS",
    "IntegrityReport",
    "Job",
    "JobCreate",
    "JobEventCreate",
    "JobEventRecord",
    "JobRecord",
    "JobRepository",
    "Message",
    "MessageCreate",
    "MessageRecord",
    "MessageRepository",
    "Migration",
    "MigrationReport",
    "MigrationRunner",
    "Project",
    "ProjectCreate",
    "ProjectRecord",
    "ProjectRepository",
    "ResearchRepository",
    "ResearchSearchRecord",
    "SourceRecord",
    "StorageError",
    "StorageErrorCode",
    "TimelineVersion",
    "TimelineVersionCreate",
    "TimelineVersionRecord",
    "TimelineVersionRepository",
    "deserialize_json_value",
    "discover_migrations",
    "migration_checksum",
    "new_id",
    "normalize_migration_text",
    "serialize_json_value",
    "utc_now_ms",
]
